version: "3"
services:
  db:
    image: mysql:5.7.30
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: textbooxDB
    volumes:
      - mysql_vol:/var/lib/mysql
    ports:
      - "4306:3306"

  web:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./:/app
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    depends_on:
      - db
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

volumes:
  mysql_vol:
  gem_data:
