# circleCIのバージョン指定
version: 2
# jobsの設定（実際に実行するコマンド郡）
jobs:
  build:
    # machine:
    #   image: circleci/classic:edge
    docker:
      - image: circleci/ruby:2.7.2
        # auth:
        #   username: mydockerhub-user
          # password: password
        environment:
          DB_HOST: 127.0.0.1
          RAILS_ENV: test
      - image: circleci/mysql:5.7.30
        # auth:
        #   username: mydockerhub-user
        #   password: password
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd

      # working_directory: ~/textboox  #自身のアプリディレクトリ名を設定  

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          gem install bundler -v 2.0.2
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}

    # Database setup
    - run: mv ./config/database.yml.ci ./config/database.yml

    # Database setup
    - run:
        name: Databasesetup
        command: |
           bundle exec rake db:create
           bundle exec rake db:schema:load

    - run:
        name: test
        command: bundle exec rspec
 

# EC2にSSH接続し、デプロイを実行
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      # CircleCIに登録した秘密鍵を呼び出す。
      - add_ssh_keys
      - run:
          # ssh ${USER_NAME}@${HOST_NAME} 'cd textboox && sudo git pull origin master && docker-compose restart'
          command: ssh ${USER_NAME}@${HOST_NAME} 'cd textboox && docker-compose run web bundle exec rails assets:clobber RAILS_ENV=production && docker-compose run web bundle exec rails assets:precompile RAILS_ENV=production && sudo git pull origin master && docker image prune -f && docker-compose down && docker-compose build && docker-compose up -d'

# 定義したjobsをどう動かすか設定する
# テストが成功した場合のみ、deployを実行するようにします。
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
      # CircleCI上で設定した環境変数を呼び出し
          context: textboox
          requires:
            - build
          # masterブランチがpushされた場合のみdeployするようにする。
          filters:
            branches:
              only: master















